on: 
  push:
    branches:
    - master
name: Build/Deploy
jobs:
  build:
    name: Backend (Lambda)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Backend (Lambda)
      uses: ./.github/backend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: us-east-2
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: '"cd server; ./deploy.sh"'
    - name: Frontend (S3)
      uses: ./.github/frontend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: us-east-2
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: '"cd client ; yarn install && yarn deploy"'
